---
name: AMR2MQTT
version: "2026.04.13"
slug: amr2mqtt
description: "Advanced Meter Reader to MQTT bridge"
url: https://github.com/alvinchen1/hassio-addons/tree/main/amr2mqtt
arch:
  - amd64
  - aarch64
  - armv7
build_from:
  amd64: ghcr.io/home-assistant/amd64-base:3.19
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  armv7: ghcr.io/home-assistant/armv7-base:3.19
image: ghcr.io/mdegat01/amr2mqtt/{arch}
startup: services
init: false
stage: stable
host_network: true

options: {}
schema: {}
